### ISSUE TITLE
disableCalendar does not exist on type DatePickerProps

### ISSUE THREAD

**Issue by danilov-v** [wojtekmaj/react-date-picker#256] opened 2020-04-13 14:33 UTC
Hi, Am using DatePicker in my react ts app. Am trying to use disableCalendar prop and got error.

Any help is would be highly appreciated.
![Screenshot from 2020-04-13 17-32-25](https://user-images.githubusercontent.com/48569492/79128833-d46d4800-7dac-11ea-81f4-b219ab61b6c2.png)

**Comment by wojtekmaj** [comment] 2020-04-17 10:19
Seems to be tightly connected with #255 - basically the same issue, only a different calendar prop we saw the message for - so I'm closing this as a duplicate of #255.

**Closed as completed by wojtekmaj** 2020-04-17 10:19 UTC
Labels: bug, duplicate, help wanted
