### ISSUE TITLE
Return undefined if invalid date

### ISSUE THREAD

**Issue by millscan** [wojtekmaj/react-date-picker#381] opened 2021-09-01 08:30 UTC
Hello, thanks for all of your work on this library!

Currently, if you select a date and then change one of the inputs to an invalid date, onChange doesn't fire and the previous valid date remains. 

Could we make it possible to fire an onChange event when one of the inputs changes, so that an invalid date will aways return undefined? 

Alternatively, exposing onChange handlers for day/month/year inputs will allow developers to have more granular control if necessary. 

I would be willing to submit a pull request for this functionality.

Thanks!

**Comment by wojtekmaj** [comment] 2021-09-01 08:52
It's not as easy as it sounds, and has already been attempted in https://github.com/wojtekmaj/react-date-picker/pull/250.

**Comment by wojtekmaj** [comment] 2021-09-01 08:53
Duplicate of #234

**Closed as completed by wojtekmaj** 2021-09-01 08:53 UTC
Labels: duplicate, enhancement
