### ISSUE TITLE
Disable Saturdays, Sundays and current day

### ISSUE THREAD

**Issue by FrancoPaez** [wojtekmaj/react-date-picker#384] opened 2021-09-13 22:51 UTC
Hi! I wanted to know if there is any way to make Saturdays and Sundays not selectable. I hope so because I like the component but if it does not have such action they will force me to change it. Thank you :)

**descriptive image**

![Captura](https://user-images.githubusercontent.com/82821596/133167031-f64d1835-bbcb-4da6-9ff9-b1074f0ff187.PNG)

Extra: By the way, something else I wanted to know was if I could also make the day after the current day be selected as the minimum date.

**Comment by wojtekmaj** [comment] 2021-09-13 23:12
Duplicate of #198

**Closed as completed by wojtekmaj** 2021-09-13 23:12 UTC
Labels: question
