### ISSUE TITLE
Formate

### ISSUE THREAD

**Issue by alokKumarSingh89** [wojtekmaj/react-date-picker#127] opened 2018-12-26 08:19 UTC
Now able to change date format.
Like i want format in DD/MM/YYYY but you this taking MM/DD/YYYY.

Can you help me.

**Comment by wojtekmaj** [comment] 2018-12-27 14:30
Duplicate of #40. See also #90.

**Closed as completed by wojtekmaj** 2018-12-27 14:30 UTC
Labels: duplicate, question

**Comment by wojtekmaj** [comment] 2019-03-31 18:58
Hi everyone,
React-Date-Picker 7.5.0 is out and supports `format` prop! Please refer to README for more details and list of supported tokens.

Happy coding!
