### ISSUE TITLE
Wrong date is selected

### ISSUE THREAD

**Issue by OZZlE** [wojtekmaj/react-date-picker#353] opened 2021-04-07 06:01 UTC
I'm saving the date in localStorage and I noticed that it always saves the day before...

So if I select: 1970-01-01 it instead stores this:

1969-12-31T23:00:00.000Z

Work around for now I found was to do this:

    const onBirthDateChange = (date: Date | Date[]):void => {
      if (!(date instanceof Date)) {
        return
      }

      // fix - otherwise it sets the day before at 23 PM ??
      date.setHours(12) // temp fix for this bug

      // save result
    }

**Comment by wojtekmaj** [comment] 2021-04-07 07:15
Duplicate of #222 
Duplicate of #263

**Closed as completed by wojtekmaj** 2021-04-07 07:15 UTC
Labels: duplicate, question
