### ISSUE TITLE
Minutes and seconds field input manually 

### ISSUE THREAD

**Issue by shanmukhirukunaga** [wojtekmaj/react-date-picker#349] opened 2021-02-26 16:36 UTC
when I try to enter minutes field manually,  from 01 to 09 it is showing numbers as 001,002,003,004,005,006,007,008,009.
I have attached a screenshot, plz check it
![image](https://user-images.githubusercontent.com/76225434/109327490-67588900-787e-11eb-9358-328b679db29e.png)

**Comment by wojtekmaj** [comment] 2021-03-01 13:37
Duplicate of #185

**Closed as completed** 2021-03-01 13:37 UTC
Labels: bug, duplicate
