### ISSUE TITLE
Manually input zeroes are preserved even with showLeadingZeros set to true

### ISSUE THREAD

**Issue by EngiN33R** [wojtekmaj/react-date-picker#156] opened 2019-05-15 15:59 UTC
If showLeadingZeros is set to true and e.g. "05" is entered in the day or month field, the zero is preserved alongside the component's leading zero. I fixed this in a pull request I created last year for a previous version (#89), but sadly the PR went unnoticed.

**Comment by wojtekmaj** [comment] 2019-07-27 15:28
Hi,
sorry for the delay.
React-Date-Picker tries to copy native date picker's behavior as closely as possible. With this in mind, I'm planning to support the behavior when user enters "00" ([try it!](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_date)).

Your PR indeed fixes the issue you're describing, but may prevent from implementing the behavior I described above. Additionally, #89 prevents from typing year like '0000' which is possible in native input.

When my problem is solved, the problem being discussed here would go away as a side effect - as soon as the user enters two zeros, input changes to '1' and everything's fine. Unfortunately, it's a complicated problem for me to solve and I'm having a really hard time solving this in an elegant way.

**Comment by wojtekmaj** [comment] 2021-03-10 19:02
Duplicate of #185

**Closed as completed by wojtekmaj** 2021-03-10 19:02 UTC
Labels: bug, duplicate
