### ISSUE TITLE
Custom input formating

### ISSUE THREAD

**Issue by Arseniy-II** [wojtekmaj/react-date-picker#121] opened 2018-12-05 11:01 UTC
Hi @wojtekmaj ! 
Really nice and lightweight date-picker. I love it! But it would be really nice to have an option to format input value differently.
![screen shot 2018-12-05 at 12 53 48](https://user-images.githubusercontent.com/22207770/49509143-2fc02980-f88d-11e8-8ced-7e98303a5b8b.png)
So I could have something like: `May 12 2018` instead of `12/05/2018`.
Hope it is possible :)

**Comment by wojtekmaj** [comment] 2018-12-06 12:33
Duplicate of #40

**Closed as completed by wojtekmaj** 2018-12-06 12:33 UTC
Labels: enhancement

**Comment by dorsharon** [comment] 2018-12-11 11:05
can it be done?
is there any way to manipulate the date to display like '26-Dec-2018'?

**Comment by wojtekmaj** [comment] 2019-03-31 18:57
Hi everyone,
React-Date-Picker 7.5.0 is out and supports `format` prop! Please refer to README for more details and list of supported tokens.

Happy coding!
